<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pge_General</name>
   <tag></tag>
   <elementGuidId>19cae21f-11a4-4f9a-901f-1f1d51af058f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active > a.waves-effect.waves-themed > span.nav-link-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='js-nav-menu']/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;  General &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0b4cbd4-c247-431a-9bcb-0210d4aa157a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-text</value>
      <webElementGuid>67f6a3c5-26b4-42de-bc67-0226b798d9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>nav.general</value>
      <webElementGuid>e63685db-f35e-449b-a895-6b80f35e93c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General</value>
      <webElementGuid>5fcbf74f-c010-4963-bb24-9d5aaf03c1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-nav-menu&quot;)/li[@class=&quot;active&quot;]/a[@class=&quot;waves-effect waves-themed&quot;]/span[@class=&quot;nav-link-text&quot;]</value>
      <webElementGuid>3f7c60a3-7bd9-422b-976a-2ff046b2c08a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js-nav-menu']/li[2]/a/span</value>
      <webElementGuid>119f7767-1f9c-4499-b6a2-d1a7b38641f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::span[1]</value>
      <webElementGuid>82391c2e-3c70-4e7a-aa7e-548142a74b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wiseenergy India Limited'])[1]/following::span[2]</value>
      <webElementGuid>1351d212-45c5-435c-b469-b10c0f2a8d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Key Asset Action'])[1]/preceding::span[1]</value>
      <webElementGuid>37aeb164-da3a-4fbe-b931-ea446ebb14bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Key Action'])[1]/preceding::span[2]</value>
      <webElementGuid>3846c173-5e0c-43f2-ac12-40d72a93544e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='General']/parent::*</value>
      <webElementGuid>1ca9996b-a0a7-4532-802d-b38feaa04659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>8b77d2fa-e6ec-4590-8f97-99a0d3978292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'General' or . = 'General')]</value>
      <webElementGuid>300b00bc-350d-467a-b3e6-2e9ee2a1af7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
