<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_CommercialInformed</name>
   <tag></tag>
   <elementGuidId>536ef12a-fe8d-4071-80f9-b543cfcb0c55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#commercial_dept_informed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='commercial_dept_informed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Commercial&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc0debc0-a215-454a-b286-8193ae1c628f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>66a4cdbf-c640-495c-8578-04928c4de062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>52c7aea8-b2c4-4d30-9891-0880df87c383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>commercial_dept_informed</value>
      <webElementGuid>cbc8f7df-a133-4963-bccb-d1ad18f2112e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commercial_dept_informed</value>
      <webElementGuid>7d270a40-a051-489a-9e26-0884c58f724c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5c9f3624-3b2b-4d80-b7f1-3a8e85a10c55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commercial_dept_informed&quot;)</value>
      <webElementGuid>90e102c4-0745-4391-9261-03c942d29122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='commercial_dept_informed']</value>
      <webElementGuid>f8053772-9272-4309-9d61-60803fbead9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[12]/div/div[2]/div/input</value>
      <webElementGuid>bead73fb-ec19-4cd3-b244-46e4b2194416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/div/input</value>
      <webElementGuid>7d770dc0-73fa-4015-866c-0572743f2ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'commercial_dept_informed' and @name = 'commercial_dept_informed']</value>
      <webElementGuid>5bd7be22-73e7-4883-b2c4-b6844cb18ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
