<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_EsgInformed</name>
   <tag></tag>
   <elementGuidId>508771c0-8fac-49cd-b3b2-49ee894b8808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#esg_dept_informed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='esg_dept_informed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;ESG&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4d9beb3-56bd-4cdc-8492-affd95714b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d9826422-003c-42c9-8951-8c5594b57a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2658c07e-06e4-4d2a-949b-0d71b3be57de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esg_dept_informed</value>
      <webElementGuid>07ef85a7-3f26-41ea-981d-d6f1cec631ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>esg_dept_informed</value>
      <webElementGuid>3e9b669b-3c30-455a-9606-2bc686afaa9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ef185c80-90db-449e-8d7f-178439b1375d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esg_dept_informed&quot;)</value>
      <webElementGuid>79b7e00f-f29c-428e-ae60-eaf84bce04e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='esg_dept_informed']</value>
      <webElementGuid>8605ae5e-52ac-4f00-a56c-7b91544b8c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[12]/div/div[5]/div/input</value>
      <webElementGuid>e0b1076b-1d3d-4cf7-a8e5-0541c8252ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>1a95e99d-ebee-46e8-8123-cd4b81d66744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'esg_dept_informed' and @name = 'esg_dept_informed']</value>
      <webElementGuid>6b469010-4803-474c-b638-56d5897bb435</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
