<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_HseInformed</name>
   <tag></tag>
   <elementGuidId>92b17e0c-4812-46d5-a6fa-0d27142b8564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hse_dept_informed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hse_dept_informed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;HSE&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64c9dc15-77ef-469a-8669-aaba4e3ba00a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>1a2f92bf-1a8f-4732-b129-37328d0b696d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>aa639936-a6d0-4b92-b375-865dac6c483a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hse_dept_informed</value>
      <webElementGuid>9d9fc050-89ac-43f4-8161-faa8fc9fcf03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hse_dept_informed</value>
      <webElementGuid>adedb447-b1ff-4f4c-b67c-2d188a475038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2cad81a0-3804-4f71-9313-a870186e6e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hse_dept_informed&quot;)</value>
      <webElementGuid>9d85af51-eb33-4eaf-8e05-d6afa130cf10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hse_dept_informed']</value>
      <webElementGuid>f52eea89-c019-4d61-9faf-2b1f9a3087c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[12]/div/div[8]/div/input</value>
      <webElementGuid>526d940f-7d46-4590-9faf-60ab5fe42305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>775981e1-2b59-467d-b49a-5aadc3c12dc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'hse_dept_informed' and @name = 'hse_dept_informed']</value>
      <webElementGuid>5e21d735-91ed-4687-b05b-dd825260b24f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
