<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_DebtManagementInformed</name>
   <tag></tag>
   <elementGuidId>a6da48d9-730f-40cf-a438-43eb7499f10c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#debt_management_dept_informed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='debt_management_dept_informed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Debt Management&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a33ddb0-3421-4897-a7c3-e920c0522cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>cf9cad3a-7c0b-4f34-8199-195e709af4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6a509d08-0dda-48b6-9e5c-d9659628e920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>debt_management_dept_informed</value>
      <webElementGuid>4c779375-c029-40cc-9600-ed6911a29b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>debt_management_dept_informed</value>
      <webElementGuid>d661fa07-cc1f-44cf-b153-b8106d8a5774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>429e2653-7c4c-4327-bc20-e2f0ba173645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;debt_management_dept_informed&quot;)</value>
      <webElementGuid>c9be55b3-b4d2-4339-b8c8-d57e83d12db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='debt_management_dept_informed']</value>
      <webElementGuid>cd7ae561-ccde-4426-9931-fdec893c410d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[12]/div/div[7]/div/input</value>
      <webElementGuid>958fac58-b49d-4211-b868-b0b78a825ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>750af33b-da95-415c-9003-1d0dfacbc28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'debt_management_dept_informed' and @name = 'debt_management_dept_informed']</value>
      <webElementGuid>cdd3154e-e668-45db-835a-a9ff18836dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
