<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_FinanceInformed</name>
   <tag></tag>
   <elementGuidId>ec2d1d65-9fd0-4614-b9c6-c20c861b3491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#finance_dept_informed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='finance_dept_informed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Finance&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0dad317-1553-431b-8c5a-19d91eaae50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>bae086eb-3560-4f37-82d8-fe23ce21b857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e2cc8993-9b8b-4a31-956d-d662bf3f0a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>finance_dept_informed</value>
      <webElementGuid>3c52b2bb-c673-4151-b592-3bca60e349af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>finance_dept_informed</value>
      <webElementGuid>6b385276-f050-4a15-9ca5-9d902ba4a6b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6029801f-918d-4524-8056-47676820e892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;finance_dept_informed&quot;)</value>
      <webElementGuid>a17e4cc6-5da0-4fbc-83be-6a36dacab49d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='finance_dept_informed']</value>
      <webElementGuid>15fa9c91-8c7a-4945-92f3-4de7538c0875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[12]/div/div[3]/div/input</value>
      <webElementGuid>73563280-d586-41ab-9963-dff159cfae59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[3]/div/input</value>
      <webElementGuid>29a2b9a4-7f5d-439f-814b-628629b3a2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'finance_dept_informed' and @name = 'finance_dept_informed']</value>
      <webElementGuid>f932a8ff-8f1e-4078-b9d1-776fc572f3c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
