<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_Category</name>
   <tag></tag>
   <elementGuidId>88c72b22-1e60-4df0-94c1-cde6647f24f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#action_esg_category</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='action_esg_category']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#action_esg_category</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>94a765d3-afa5-4aa8-98c7-76456243e11b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>407e2be2-a80c-4968-af6c-d33bde7821b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>action_esg_category</value>
      <webElementGuid>7aaa9f45-9786-4d73-ab43-31dc9e6aeaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action_esg_category</value>
      <webElementGuid>9eb95774-4018-4cb7-82f6-64f32b398791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    AuditMonitoringEngagement planManagement planPolicyLand managementESG and H&amp;S incidentBiodiversityContractOperating budgetAcquisition budgetOpEx costCapEx costOther                </value>
      <webElementGuid>f299cf0f-2b93-40f7-82dd-da6659ab3179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action_esg_category&quot;)</value>
      <webElementGuid>28f423c0-143f-4114-b0a1-2bac844499a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='action_esg_category']</value>
      <webElementGuid>44b689ac-348e-4e7f-90e6-41c9c558ab5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_content']/div/div/div/select</value>
      <webElementGuid>82d49b58-995e-4163-9543-5f77e3d3938d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category'])[1]/following::select[1]</value>
      <webElementGuid>fb1b3679-f5f3-4b30-9b3d-69dd1de01afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description required.'])[1]/following::select[1]</value>
      <webElementGuid>ce02f295-3215-453f-9ec5-c9aa0e04e184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frequency'])[1]/preceding::select[1]</value>
      <webElementGuid>c96e98fa-1037-481e-909c-32b3d2ced708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::select[2]</value>
      <webElementGuid>0f10475f-75f2-4e08-8227-4ebe3c4fae43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a6c3fea7-51a2-4102-868a-4aceb08c96ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'action_esg_category' and @name = 'action_esg_category' and (text() = '
                    AuditMonitoringEngagement planManagement planPolicyLand managementESG and H&amp;S incidentBiodiversityContractOperating budgetAcquisition budgetOpEx costCapEx costOther                ' or . = '
                    AuditMonitoringEngagement planManagement planPolicyLand managementESG and H&amp;S incidentBiodiversityContractOperating budgetAcquisition budgetOpEx costCapEx costOther                ')]</value>
      <webElementGuid>5756e43a-d2b7-4961-8125-c5082f27f6f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
