<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_Status</name>
   <tag></tag>
   <elementGuidId>eed66ebb-3a99-4c12-8177-23538e7a5a03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currentstatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='currentstatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#currentstatus</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48370467-11ed-4be5-975e-7f1b28a23dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>945ff2dc-b3b1-4a42-87fb-4a0a2af8dac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentstatus</value>
      <webElementGuid>6c520b37-983c-4fc3-b157-e387c7bd3ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentstatus</value>
      <webElementGuid>af35c882-f406-4fc4-a5f8-87be61915003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    UndefinedOpenClosedOn holdCancelled                </value>
      <webElementGuid>c6b71469-e759-4b5d-8f0e-993ec095ec85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentstatus&quot;)</value>
      <webElementGuid>22d8ef7d-aa8b-4ca4-b9b0-a4b0a85746da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='currentstatus']</value>
      <webElementGuid>8785602c-5d62-48b8-9ad2-4e4adbbeceae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[4]/select</value>
      <webElementGuid>7c0b9877-8831-4318-afc7-ada7f8574ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>7c70b199-c246-4f9d-8d37-dccd115fe175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[1]/following::select[2]</value>
      <webElementGuid>c67ef4cc-20a0-4963-a05e-1a7029f6c016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsible By'])[1]/preceding::select[1]</value>
      <webElementGuid>23a9ff44-c9c4-4957-8b2c-07d080db974c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsible By is required.'])[1]/preceding::select[2]</value>
      <webElementGuid>ccda7f62-00b1-4fa8-90a7-2b459d160a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>934a1687-805e-4534-a5bb-85b39ef9815d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'currentstatus' and @name = 'currentstatus' and (text() = '
                    UndefinedOpenClosedOn holdCancelled                ' or . = '
                    UndefinedOpenClosedOn holdCancelled                ')]</value>
      <webElementGuid>7cb1a79e-8e3f-4ead-8fc9-7c1d92b349b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
