<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_Priority</name>
   <tag></tag>
   <elementGuidId>4f5ca571-2dfa-493b-84d2-bd3adcec455d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#priority</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='priority']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Priority&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c4571019-4dae-4e34-a363-590e126a8b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>priority</value>
      <webElementGuid>c6b06d5a-6190-4fa1-a055-c6fc6c31621f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>priority</value>
      <webElementGuid>1ce2e882-ab44-4fef-bc43-796c640d959b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control greenText</value>
      <webElementGuid>f8dba4dc-7570-4421-bbc6-fd54cb2655bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Low
                    Medium
                    High
                    Critical
                    </value>
      <webElementGuid>435b72c7-aedb-4af7-bf36-73ba80c72ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;priority&quot;)</value>
      <webElementGuid>40cc0899-7e0c-4f43-a5e1-a4c8287f7185</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='priority']</value>
      <webElementGuid>cee4a411-7bf5-44b5-a1d3-39286e82deb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[3]/select</value>
      <webElementGuid>bcb0869c-a5e2-41ba-97bd-46e1e4bcf446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Priority'])[1]/following::select[1]</value>
      <webElementGuid>8a43171d-ef66-4cf9-8d59-6697948a1b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset is required.'])[1]/following::select[1]</value>
      <webElementGuid>980dcb65-ae03-49a3-81cf-081a3f4ddebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>9f47644e-5405-4145-9392-8d1625850a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsible By'])[1]/preceding::select[2]</value>
      <webElementGuid>ac5c6914-4dc2-4bca-bc3f-6c6a25f3eecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>259975b0-b7e1-479d-8b9e-510ef4c3b01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'priority' and @name = 'priority' and (text() = '
                    Low
                    Medium
                    High
                    Critical
                    ' or . = '
                    Low
                    Medium
                    High
                    Critical
                    ')]</value>
      <webElementGuid>c58fcd75-9f64-428b-9a08-91aa06281287</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
