<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_OperatingBudget</name>
   <tag></tag>
   <elementGuidId>b6853626-ebd2-47ab-99fe-32fb1125f88b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operating_budget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='operating_budget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#operating_budget</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca5d4762-05cd-48b6-9bc0-4ac5554774e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2b96ae06-df04-4b1a-847e-e80656c05c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operating_budget</value>
      <webElementGuid>f787bdf8-09c5-4892-abea-aeb55f714f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>operating_budget</value>
      <webElementGuid>25d9b6fa-aa78-482b-a8e6-4781ec562bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>27c124fe-d76f-468e-9b4a-c4cb708a3012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateMaxValue(this)</value>
      <webElementGuid>3b03dfd1-356d-4842-8c01-015127caa9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999999.99</value>
      <webElementGuid>2349ac97-ea15-46c2-93f5-237a9f39081b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>dd676198-9e2b-4939-9d0a-b9187b173068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operating_budget&quot;)</value>
      <webElementGuid>ef96b7e3-7c0c-4b33-af3f-35b89d876d55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='operating_budget']</value>
      <webElementGuid>a22ee07a-9940-4946-b9a6-c4de26a3ebfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_content']/div/div[3]/div[2]/input</value>
      <webElementGuid>05a6d925-4fc1-46a5-af1b-6da3a504ddeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>2f1c06be-7b3a-48bd-b63c-4e99daeea51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'operating_budget' and @name = 'operating_budget']</value>
      <webElementGuid>47dacf56-68f4-453b-9932-666753f6d165</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
