<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_AcquisitionBudget</name>
   <tag></tag>
   <elementGuidId>8f36abe1-5254-4f03-95a4-39bb06161f7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acquisition_budget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acquisition_budget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#acquisition_budget</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30c01db2-bb85-408d-afcc-449cda35a1d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>96059491-06dc-4b38-8331-a3fba699a781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acquisition_budget</value>
      <webElementGuid>17300310-888d-4cff-bfbb-3fa863f25836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>acquisition_budget</value>
      <webElementGuid>0346e347-54b3-4b97-9c79-50d73e3a8d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c2766a58-f09a-4e2e-9e3d-3f58ebfadc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateMaxValue(this)</value>
      <webElementGuid>537ca951-365c-43fd-9dba-915e20527872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999999.99</value>
      <webElementGuid>2aca432c-ac13-40e7-b978-6e5808206093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>b748a2ec-35f1-4e74-a9d4-312d481aca8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acquisition_budget&quot;)</value>
      <webElementGuid>3d9314e8-1325-4b7b-9fca-be1d4bc2931a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acquisition_budget']</value>
      <webElementGuid>1ba49fbd-fe0a-47dd-bdd9-5d7bcbce8bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_content']/div/div[3]/div/input</value>
      <webElementGuid>9a23ce2f-6f2c-450b-bf8f-739a8bfbb529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>6c071ac7-b30a-4ceb-a95c-ab7c0f8a8f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'acquisition_budget' and @name = 'acquisition_budget']</value>
      <webElementGuid>fb7d081a-fd59-4b0d-afa1-8fbd88bf47f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
