<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_EndDate</name>
   <tag></tag>
   <elementGuidId>f73a7350-e897-469e-a057-e41abaabf276</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enddate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='enddate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;End Date and Time&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03aa4096-09e8-4a00-a75f-a2d419a09a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>34c5e3eb-8218-4553-829c-4a2ec59a2f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enddate</value>
      <webElementGuid>faf4ae39-9caa-45e0-9c53-9add5e40ff3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enddate</value>
      <webElementGuid>0089de60-b16d-44fb-b742-13f0cae45387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datetime-picker</value>
      <webElementGuid>15b26fef-5403-4684-bdf5-ea35ea0edea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy hh:mm</value>
      <webElementGuid>f5759d81-d6c7-4612-885c-c4e6a078a22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enddate&quot;)</value>
      <webElementGuid>4e03be8d-6b4d-4bd5-9dce-c82538739af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='enddate']</value>
      <webElementGuid>e7a6e4d0-df2d-4620-a9a9-58077db34cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[8]/input</value>
      <webElementGuid>841b5837-829b-416b-892c-19bd2941b6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>73b2de8f-009a-4005-8d5f-9b68c8ccb02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'enddate' and @name = 'enddate' and @placeholder = 'dd/mm/yyyy hh:mm']</value>
      <webElementGuid>928a4aed-4c51-4a14-ac2c-b98b22fa697b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
