<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ActualOpExcost</name>
   <tag></tag>
   <elementGuidId>ed715441-cc56-4a0e-861d-98afa1de34af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actual_opex_cost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actual_opex_cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#actual_opex_cost</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92d2b306-deea-4ffd-a57c-475fafa9ab15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>33d2acc1-3259-4fe5-984c-f06492eb089c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actual_opex_cost</value>
      <webElementGuid>2b93b9bf-d4e3-4965-afa4-572f0dd0e676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actual_opex_cost</value>
      <webElementGuid>e60c61c6-5b77-469b-9333-c4551fcce933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>10ca67f1-a51c-4c20-86a7-28fae7c424f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateMaxValue(this)</value>
      <webElementGuid>2f46a4aa-2372-4a1f-9ced-c090fb82b122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999999.99</value>
      <webElementGuid>eefcdc53-7cbe-42cd-8aba-aab1944ea571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>4a0ac3b4-f6f6-47eb-a3bf-abaa91dd2781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actual_opex_cost&quot;)</value>
      <webElementGuid>4ca04df9-6828-410e-9ab1-edaa788881dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actual_opex_cost']</value>
      <webElementGuid>908ee783-585a-41bb-859e-5a466ad85f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_content']/div/div[2]/div/input</value>
      <webElementGuid>3033e63f-a1c4-49e4-86bb-3be347c13715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>2f08c58f-49fd-4748-aa7b-a4b1efb399f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'actual_opex_cost' and @name = 'actual_opex_cost']</value>
      <webElementGuid>a3bd1710-7ec8-43b4-a66a-ff580b91bf27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
