<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lstSelectExistingAccount</name>
   <tag></tag>
   <elementGuidId>1fa2e2f8-1f4d-4909-8892-9ae2464fc474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromAccountId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fromAccountId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#fromAccountId</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a1109049-af3a-471b-b17a-7ef181d5fbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromAccountId</value>
      <webElementGuid>bd2e2ace-f687-4f13-affd-0baed7056834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f891ffbc-d1fc-4a38-b16f-66855e459f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1367715231</value>
      <webElementGuid>f1a90db1-a355-4c66-8eb1-a7cd21e2c108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromAccountId&quot;)</value>
      <webElementGuid>1d3071c3-ab65-4f78-b499-00a1209ffe35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fromAccountId']</value>
      <webElementGuid>626e59e6-b71e-4d98-8bcc-a3fe6b76c606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='openAccountForm']/form/select[2]</value>
      <webElementGuid>7e3bd0e0-5826-4a83-b8a8-452a1a14290c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What type of Account would you like to open?'])[1]/following::select[2]</value>
      <webElementGuid>07ae3669-63a3-46fb-9764-64c8a53a90cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open New Account'])[2]/following::select[2]</value>
      <webElementGuid>ff9abdc8-f9b0-4940-9ead-589ae4462bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Opened!'])[1]/preceding::select[1]</value>
      <webElementGuid>c48ea83c-370b-40fa-80fe-f37ebca26dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your new account number:'])[1]/preceding::select[1]</value>
      <webElementGuid>03ea8f3d-aa58-4a22-a23a-63ddb8d26e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>1f04cd74-c330-4cb2-81a3-7352096a6312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'fromAccountId' and (text() = '1367715231' or . = '1367715231')]</value>
      <webElementGuid>ce0a9bee-40e9-4b67-84a3-c5e6ffd75171</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
