<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtConfirmPassword</name>
   <tag></tag>
   <elementGuidId>2d4ff60f-54aa-4d6c-b4ea-24ffb4029e7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repeatedPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repeatedPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#repeatedPassword</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6f210f2-93e3-4cc8-b5f9-79ef9f469574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>3aa5a543-65a5-4493-9fd8-8954305b11f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>3f90f375-c762-4b47-b868-7d2cefd279e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff73c8ab-a204-41bd-aae4-922dade7f713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5700e262-96e4-4308-bd37-32d0155fdbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeatedPassword&quot;)</value>
      <webElementGuid>2ac504fb-e5d6-4dbb-852e-54886a702414</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repeatedPassword']</value>
      <webElementGuid>77e87a7b-cb32-486a-8c49-f0efaf17a80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerForm']/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>8c5456b2-4cca-4b5e-b8f3-ed862c00e01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/input</value>
      <webElementGuid>4e23dc0a-c8cf-4715-b7f6-018b70cb1fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'repeatedPassword' and @name = 'repeatedPassword' and @type = 'password']</value>
      <webElementGuid>953a2a72-9f29-49cb-807f-9ac0c730b026</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
