<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_TechnicalInformed</name>
   <tag></tag>
   <elementGuidId>dbdea44a-17e6-4c38-b1dc-424d10546bf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#technical_dept_informed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='technical_dept_informed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Technical&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b037adf0-4643-4e5f-909f-11bbd371d22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>ff3e6b26-a169-45c7-8468-954af479c0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e7d9a327-0a8a-4e0c-a5cf-fa711974a4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>technical_dept_informed</value>
      <webElementGuid>a1ccc426-552b-4e3d-8896-d4aceec3954c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>technical_dept_informed</value>
      <webElementGuid>2cf1938e-6d54-4c15-a7fa-dbcfa228246b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8147ce9e-6da2-445d-b3cf-7c0c45dd63ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;technical_dept_informed&quot;)</value>
      <webElementGuid>a4ec5cc1-34ac-48de-beed-079c873571ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='technical_dept_informed']</value>
      <webElementGuid>e3e383b9-7277-49d1-887b-3fbfe881c1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[12]/div/div[4]/div/input</value>
      <webElementGuid>31fae796-e76b-4aa5-a1f6-335890065e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[4]/div/input</value>
      <webElementGuid>34a6b0e7-734a-4037-a6d7-1bfe93e8212b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'technical_dept_informed' and @name = 'technical_dept_informed']</value>
      <webElementGuid>a7e1d3ba-358b-4235-80e0-348ddd8cf1fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
