<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_SiteManagementDeptInformed</name>
   <tag></tag>
   <elementGuidId>ddfad658-0f68-4edf-8c1c-7258b4f9ac56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#site_management_dept_informed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='site_management_dept_informed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Site Management&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dbc0c6b-ce60-4892-ad49-b7bcf014b877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>99e593f2-93a1-4700-beff-f2c4b56d94f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>13ccb9fa-72c0-4296-a94e-3288a1df35aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>site_management_dept_informed</value>
      <webElementGuid>73847c82-fceb-4b86-b523-aedd4c6f9bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>site_management_dept_informed</value>
      <webElementGuid>efa173e2-1114-42cf-8c71-041c38c0138f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bbf57a06-eb49-46bc-9b2c-6f38e0299c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site_management_dept_informed&quot;)</value>
      <webElementGuid>ffc1672c-cb2b-4007-bed7-b5e501796aa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='site_management_dept_informed']</value>
      <webElementGuid>f8c5d1f1-fb33-494b-8c4c-0f8ac8d714f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[12]/div/div[10]/div/input</value>
      <webElementGuid>1e4669f2-69b3-4c12-a072-d41f45e267f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>c9f7d8b2-5c1b-45ec-a7df-ec83d636deb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'site_management_dept_informed' and @name = 'site_management_dept_informed']</value>
      <webElementGuid>e48129da-8b86-413e-915f-76b1eb77d93b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
