<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_Module</name>
   <tag></tag>
   <elementGuidId>71d6aa3e-3a25-48f5-80cf-76afc12ccc19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#module</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='module']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#module</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d7f908c-e80c-4416-bbef-1053d1ee37dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e7101ad5-4f8e-4ec5-b1a7-1e82d297d287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>module</value>
      <webElementGuid>c7ef88b7-1cd3-4b72-b89d-dd058d85930f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>module</value>
      <webElementGuid>8522e1cc-534b-46a5-92fd-a4e8bd14f083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>loadModuleSpecificView();</value>
      <webElementGuid>db139302-ffaf-478a-92d0-fccec00c9614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Commercial ESGCommercial TrackersCommunicationsConnectivityESGG59Grid and Major OutagesHealth and SafetyInsurance claimInvoicingKnown Defects ListLand ManagementManual inputMoMonitoringO&amp;MO&amp;M ContractPAC/IAC/FACPreventive MaintenanceReportingSecurity/CCTVSite visitSolar SPVSolarPlantSpare partsTheftWarranty claimWeather sensors                    </value>
      <webElementGuid>cbd2e992-f145-42ec-9c60-45a725c4bd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;module&quot;)</value>
      <webElementGuid>c436b8c5-5cd0-4be0-be58-ad4aa3d5da2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='module']</value>
      <webElementGuid>fd4e3416-9fe3-45dc-bf85-1e7a15602c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div/select</value>
      <webElementGuid>341fd4c6-7052-4bd7-8605-29e7ce8c6da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Module'])[1]/following::select[1]</value>
      <webElementGuid>5b9b5501-821f-4dd6-8a59-55f4160dcb71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::select[1]</value>
      <webElementGuid>e1f492da-82c1-4c64-87a5-efb4013c0959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset'])[1]/preceding::select[1]</value>
      <webElementGuid>295407a4-11ee-47b9-9eda-530848089cc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asset is required.'])[1]/preceding::select[2]</value>
      <webElementGuid>e50d87be-0d28-4193-9a38-8885d470d91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>d60353cf-359f-43ff-8173-1c4841c2482c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'module' and @name = 'module' and (text() = '
                        Commercial ESGCommercial TrackersCommunicationsConnectivityESGG59Grid and Major OutagesHealth and SafetyInsurance claimInvoicingKnown Defects ListLand ManagementManual inputMoMonitoringO&amp;MO&amp;M ContractPAC/IAC/FACPreventive MaintenanceReportingSecurity/CCTVSite visitSolar SPVSolarPlantSpare partsTheftWarranty claimWeather sensors                    ' or . = '
                        Commercial ESGCommercial TrackersCommunicationsConnectivityESGG59Grid and Major OutagesHealth and SafetyInsurance claimInvoicingKnown Defects ListLand ManagementManual inputMoMonitoringO&amp;MO&amp;M ContractPAC/IAC/FACPreventive MaintenanceReportingSecurity/CCTVSite visitSolar SPVSolarPlantSpare partsTheftWarranty claimWeather sensors                    ')]</value>
      <webElementGuid>c05c3412-b257-4722-aeb2-1b9a4fff34b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
