<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_WaitingFor</name>
   <tag></tag>
   <elementGuidId>16f17c57-f1b0-4824-9bbb-76217fd19876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#waitingfor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='waitingfor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Waiting For&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b26c2d97-c0ef-46c7-a250-7fbeee69c0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7da89ef0-b8b9-4123-8569-cc8decf73e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>waitingfor</value>
      <webElementGuid>a8c4922f-5527-45ed-ab65-eb215b0df23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>waitingfor</value>
      <webElementGuid>c3b36cf3-657a-48a6-bd03-f2b61e393b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    UndefinedO &amp; MClientWise-CommercialWise-FinanceWise-TechExternalEPC ContractorICP Contractor                </value>
      <webElementGuid>7742e7a3-59f2-4f65-a0b0-0ae24140b78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;waitingfor&quot;)</value>
      <webElementGuid>f435ee05-0164-4387-9fd9-cb9e5a4755f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='waitingfor']</value>
      <webElementGuid>a46a029c-ee12-4b91-8ac8-291169575caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[9]/select</value>
      <webElementGuid>e4f5ee75-c015-4294-8c5f-4a01f8237221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiting For'])[1]/following::select[1]</value>
      <webElementGuid>012933ee-6c12-4ae0-ac0a-7d4dc2907500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End date is required on closed status.'])[1]/following::select[1]</value>
      <webElementGuid>9c365bbc-02b5-4e7d-ab5d-58b4306cec78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To be shared with the Client'])[1]/preceding::select[1]</value>
      <webElementGuid>72e34279-10cb-41f0-a972-b9619b9f2512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportable'])[1]/preceding::select[1]</value>
      <webElementGuid>898567aa-2b24-40a1-a9a7-f4cdb11244db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/select</value>
      <webElementGuid>65ab214b-0b24-4583-9195-adf9c518ed09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'waitingfor' and @name = 'waitingfor' and (text() = '
                    UndefinedO &amp; MClientWise-CommercialWise-FinanceWise-TechExternalEPC ContractorICP Contractor                ' or . = '
                    UndefinedO &amp; MClientWise-CommercialWise-FinanceWise-TechExternalEPC ContractorICP Contractor                ')]</value>
      <webElementGuid>aa899d5c-29af-41a4-8753-22d70a7884b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
