<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_ResponsibleBy</name>
   <tag></tag>
   <elementGuidId>9ff23f04-cb92-4088-81f5-279030af2f84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#responsible</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='responsible']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#responsible</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>849189b5-d359-4dbd-a5fe-37a5dd9cb831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8184e0a5-b256-455f-a3d2-c4905e8b1b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>responsible</value>
      <webElementGuid>930d61fa-0608-4208-bc4a-7a5e904c523f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>responsible</value>
      <webElementGuid>376edc66-e51c-4a14-b9cc-98fccff7dd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Select
                    Admin AdminAdriana Barua CicciaAgam SaxenaAgustin MorenoAlaa ElbahriAleksandra Wiktoria DedekAlessandra FerraraAlessandra RigonAlessandro BoscarelliAlessandro MariniAlexandros AthanasiadisAmaresh GuptaAmer MohammedAmitava ChowdhuryAna RuizAna TarifaAnand StevenAndrew DiamondAndrew LevyAnna TomalaAnup ShawAnushree ChaturvediArchana EppaArun UgraAttilio FrignatiAtul IndapBalaji SekarBarbara MattaBernardo RodriguezBiplab MohantyBruno VicenteCarlos GuerreroCarmen Aguayo RamirezCatarina MaiaChakradhar Reddy KoduruCharl VisserChiara GuiducciChiara IorioChristiana BebanaConstance HauetCristina ColiDanelle BerzinsDaniel KingscoteDavid HawkinsDavide BesanaDiego MarquezDiego MolinaDimitri Van WellenEddie Font FreideEduardo JuarezEdward MurielEirini ZoupaliEmily McleanEric FleischhauerEsha BalEstefania LopezFausto PappalardoFederico BellettiFelice BasileFernando SanchezFilippo CaleyFrancisco Gómez FructuosoFranco Fontanini ParajóGabriel Meler SAR ShalomGabriele FormusoGary EastGaspare PassarelloGiacomo FrancoGianluca BoccaneraGianpaolo PasiniGiorgio Di BlasioGiuditta ProietticignittiGiuseppe DonzellaGiuseppe SalvatoreGiuseppe VotoGiuseppemattia LemetreGuiseppe TruglioHannah WildHarish ReddyHeather LizamoreHing KIN LeeHoward StoneHubert PutHugo RibeiroIgnacio PerezplaIlaria BaldoIrawo Oye-BamgboseIsabel GarciaIsabel Japon LopezJacqueline CioffiJames RobertsJasmin TanJason LevyJeffrey BarnettJennifer ClarkJesus MoranJoanne NeohJoao RaloJohn MustardeJon ElvenJonathon YatesJordon SaundersJose VeraJose Francisco Correia PascoalJoseph BakerJovana NisicJuan RamosJudit Nieto GalendeKamila MaleckaKate HaynesKavya ThokalaKiran LaidlayKranthi KumarKristina VucicLais GusmaoLakshman MadipadigaLara BaravelliLaura Mendez RochaLetizia PetracciLila MoiniLorenzo BonezziLuca BianchiLucy ZychowskaMagdalena RozanskaMajka KunowskaMałgorzata SurowiecMarcin GwizdalaMarco LabagnaraMariateresa BattagliaMarnie Winston-FletcherMartina SacchiMason TrimbleMassimiliano MarcianoMassimo Di RellaMat GaftunikMateusz PrzelomskiMateusz SierakowskiMathusorn PrakorbjanyaMax MossMichael BonteMichael NashMichele OrmandoMina GillMoises Alvarez Del AguilaMonika WilsonMrigendra RaiNabil EL AyaneNancy YeungNathan HeatonNavjit BinningNeil CopemanNicholas OlakNicolo PaschettoNitin KumarOperation And Maintenance TestOrso NicodanoOsvaldo CesaroPablo Remesal GarciaPadideh AhmadiPanos KamperidisPaolo ChisteParichaya ThomareParvez KhanPaul BarwellPaul NorrishPavan KumarPawel HojkaPierandrea PagliaraPierluigi LemmaPrasad JavvadiPraveen Kumar DokkaraPreethi PavaniPriya ShahabiRafael BevilacquaRajesh KRamachandra ReddyRamakanth KandulaRamalingeswararao MandavilliRavindra GoyalRebecca CarterRebecca HallRekha KumariRes OperationsRicardo PerezRicardo TurminoRita SantoroRobert KnoxRodrigo Beltran CubilesSaeed AbdaliSai NarayanaSammy MooreSamuele TaruschioSandra SartoriSatish KumarSatish MutyalaSebastian BarkerSerena SoresiSerena ThakerShannon TomlinSheikh AhmedShereef AbdallaSilvia StradaSilvio DistefanoSimone MandicaSlawomir SasSravani LagulaSreenivas BhumireddySreenivas Test SSOSreenivas YSreenivasula ReddySRI Krishna DomaStanislava MarusicStefano PieroniStephen RosserStratos TheodorouSudheer AllaSulwen VaughanSuneel PonugotiSylwester PustelnikTanya CavanaghTeja NarayanaThomas LukinsThomas ShapleyTimothy BellTomas LeakeTony UngerUsman ShaikUttam SahaVaibhav MehtaVaibhav SahuValeria ParrellaVamsi MenduVictor ZanniVictoria MakdesiVijayraghavan VVivek SrivatsanVolkan OzgurWendy YauYurii Lobatiuk                </value>
      <webElementGuid>f178f99d-d217-4505-abcc-85d7cfcd04f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responsible&quot;)</value>
      <webElementGuid>1cd54838-34e7-4cd5-bf78-61cb715b2f05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='responsible']</value>
      <webElementGuid>a8ff35ea-2558-400d-893a-659a4c3f112d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[5]/select</value>
      <webElementGuid>b338dd86-d6cf-4a91-a0b8-531681d9f7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsible By'])[1]/following::select[1]</value>
      <webElementGuid>2206c493-e7aa-4f41-a78e-9d2d66bcc5b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[2]</value>
      <webElementGuid>87a8d180-2317-42d4-b9c7-3cf8e6694875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Responsible By is required.'])[1]/preceding::select[1]</value>
      <webElementGuid>8bbb5faf-99fc-443e-a158-cd2604819ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Date and Time'])[1]/preceding::select[1]</value>
      <webElementGuid>b7b1f66c-ab09-42f1-9328-d47a8acceece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>3ab9ba7f-1f08-45c6-8dc7-8ef41d664c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'responsible' and @name = 'responsible' and (text() = '
                    Select
                    Admin AdminAdriana Barua CicciaAgam SaxenaAgustin MorenoAlaa ElbahriAleksandra Wiktoria DedekAlessandra FerraraAlessandra RigonAlessandro BoscarelliAlessandro MariniAlexandros AthanasiadisAmaresh GuptaAmer MohammedAmitava ChowdhuryAna RuizAna TarifaAnand StevenAndrew DiamondAndrew LevyAnna TomalaAnup ShawAnushree ChaturvediArchana EppaArun UgraAttilio FrignatiAtul IndapBalaji SekarBarbara MattaBernardo RodriguezBiplab MohantyBruno VicenteCarlos GuerreroCarmen Aguayo RamirezCatarina MaiaChakradhar Reddy KoduruCharl VisserChiara GuiducciChiara IorioChristiana BebanaConstance HauetCristina ColiDanelle BerzinsDaniel KingscoteDavid HawkinsDavide BesanaDiego MarquezDiego MolinaDimitri Van WellenEddie Font FreideEduardo JuarezEdward MurielEirini ZoupaliEmily McleanEric FleischhauerEsha BalEstefania LopezFausto PappalardoFederico BellettiFelice BasileFernando SanchezFilippo CaleyFrancisco Gómez FructuosoFranco Fontanini ParajóGabriel Meler SAR ShalomGabriele FormusoGary EastGaspare PassarelloGiacomo FrancoGianluca BoccaneraGianpaolo PasiniGiorgio Di BlasioGiuditta ProietticignittiGiuseppe DonzellaGiuseppe SalvatoreGiuseppe VotoGiuseppemattia LemetreGuiseppe TruglioHannah WildHarish ReddyHeather LizamoreHing KIN LeeHoward StoneHubert PutHugo RibeiroIgnacio PerezplaIlaria BaldoIrawo Oye-BamgboseIsabel GarciaIsabel Japon LopezJacqueline CioffiJames RobertsJasmin TanJason LevyJeffrey BarnettJennifer ClarkJesus MoranJoanne NeohJoao RaloJohn MustardeJon ElvenJonathon YatesJordon SaundersJose VeraJose Francisco Correia PascoalJoseph BakerJovana NisicJuan RamosJudit Nieto GalendeKamila MaleckaKate HaynesKavya ThokalaKiran LaidlayKranthi KumarKristina VucicLais GusmaoLakshman MadipadigaLara BaravelliLaura Mendez RochaLetizia PetracciLila MoiniLorenzo BonezziLuca BianchiLucy ZychowskaMagdalena RozanskaMajka KunowskaMałgorzata SurowiecMarcin GwizdalaMarco LabagnaraMariateresa BattagliaMarnie Winston-FletcherMartina SacchiMason TrimbleMassimiliano MarcianoMassimo Di RellaMat GaftunikMateusz PrzelomskiMateusz SierakowskiMathusorn PrakorbjanyaMax MossMichael BonteMichael NashMichele OrmandoMina GillMoises Alvarez Del AguilaMonika WilsonMrigendra RaiNabil EL AyaneNancy YeungNathan HeatonNavjit BinningNeil CopemanNicholas OlakNicolo PaschettoNitin KumarOperation And Maintenance TestOrso NicodanoOsvaldo CesaroPablo Remesal GarciaPadideh AhmadiPanos KamperidisPaolo ChisteParichaya ThomareParvez KhanPaul BarwellPaul NorrishPavan KumarPawel HojkaPierandrea PagliaraPierluigi LemmaPrasad JavvadiPraveen Kumar DokkaraPreethi PavaniPriya ShahabiRafael BevilacquaRajesh KRamachandra ReddyRamakanth KandulaRamalingeswararao MandavilliRavindra GoyalRebecca CarterRebecca HallRekha KumariRes OperationsRicardo PerezRicardo TurminoRita SantoroRobert KnoxRodrigo Beltran CubilesSaeed AbdaliSai NarayanaSammy MooreSamuele TaruschioSandra SartoriSatish KumarSatish MutyalaSebastian BarkerSerena SoresiSerena ThakerShannon TomlinSheikh AhmedShereef AbdallaSilvia StradaSilvio DistefanoSimone MandicaSlawomir SasSravani LagulaSreenivas BhumireddySreenivas Test SSOSreenivas YSreenivasula ReddySRI Krishna DomaStanislava MarusicStefano PieroniStephen RosserStratos TheodorouSudheer AllaSulwen VaughanSuneel PonugotiSylwester PustelnikTanya CavanaghTeja NarayanaThomas LukinsThomas ShapleyTimothy BellTomas LeakeTony UngerUsman ShaikUttam SahaVaibhav MehtaVaibhav SahuValeria ParrellaVamsi MenduVictor ZanniVictoria MakdesiVijayraghavan VVivek SrivatsanVolkan OzgurWendy YauYurii Lobatiuk                ' or . = '
                    Select
                    Admin AdminAdriana Barua CicciaAgam SaxenaAgustin MorenoAlaa ElbahriAleksandra Wiktoria DedekAlessandra FerraraAlessandra RigonAlessandro BoscarelliAlessandro MariniAlexandros AthanasiadisAmaresh GuptaAmer MohammedAmitava ChowdhuryAna RuizAna TarifaAnand StevenAndrew DiamondAndrew LevyAnna TomalaAnup ShawAnushree ChaturvediArchana EppaArun UgraAttilio FrignatiAtul IndapBalaji SekarBarbara MattaBernardo RodriguezBiplab MohantyBruno VicenteCarlos GuerreroCarmen Aguayo RamirezCatarina MaiaChakradhar Reddy KoduruCharl VisserChiara GuiducciChiara IorioChristiana BebanaConstance HauetCristina ColiDanelle BerzinsDaniel KingscoteDavid HawkinsDavide BesanaDiego MarquezDiego MolinaDimitri Van WellenEddie Font FreideEduardo JuarezEdward MurielEirini ZoupaliEmily McleanEric FleischhauerEsha BalEstefania LopezFausto PappalardoFederico BellettiFelice BasileFernando SanchezFilippo CaleyFrancisco Gómez FructuosoFranco Fontanini ParajóGabriel Meler SAR ShalomGabriele FormusoGary EastGaspare PassarelloGiacomo FrancoGianluca BoccaneraGianpaolo PasiniGiorgio Di BlasioGiuditta ProietticignittiGiuseppe DonzellaGiuseppe SalvatoreGiuseppe VotoGiuseppemattia LemetreGuiseppe TruglioHannah WildHarish ReddyHeather LizamoreHing KIN LeeHoward StoneHubert PutHugo RibeiroIgnacio PerezplaIlaria BaldoIrawo Oye-BamgboseIsabel GarciaIsabel Japon LopezJacqueline CioffiJames RobertsJasmin TanJason LevyJeffrey BarnettJennifer ClarkJesus MoranJoanne NeohJoao RaloJohn MustardeJon ElvenJonathon YatesJordon SaundersJose VeraJose Francisco Correia PascoalJoseph BakerJovana NisicJuan RamosJudit Nieto GalendeKamila MaleckaKate HaynesKavya ThokalaKiran LaidlayKranthi KumarKristina VucicLais GusmaoLakshman MadipadigaLara BaravelliLaura Mendez RochaLetizia PetracciLila MoiniLorenzo BonezziLuca BianchiLucy ZychowskaMagdalena RozanskaMajka KunowskaMałgorzata SurowiecMarcin GwizdalaMarco LabagnaraMariateresa BattagliaMarnie Winston-FletcherMartina SacchiMason TrimbleMassimiliano MarcianoMassimo Di RellaMat GaftunikMateusz PrzelomskiMateusz SierakowskiMathusorn PrakorbjanyaMax MossMichael BonteMichael NashMichele OrmandoMina GillMoises Alvarez Del AguilaMonika WilsonMrigendra RaiNabil EL AyaneNancy YeungNathan HeatonNavjit BinningNeil CopemanNicholas OlakNicolo PaschettoNitin KumarOperation And Maintenance TestOrso NicodanoOsvaldo CesaroPablo Remesal GarciaPadideh AhmadiPanos KamperidisPaolo ChisteParichaya ThomareParvez KhanPaul BarwellPaul NorrishPavan KumarPawel HojkaPierandrea PagliaraPierluigi LemmaPrasad JavvadiPraveen Kumar DokkaraPreethi PavaniPriya ShahabiRafael BevilacquaRajesh KRamachandra ReddyRamakanth KandulaRamalingeswararao MandavilliRavindra GoyalRebecca CarterRebecca HallRekha KumariRes OperationsRicardo PerezRicardo TurminoRita SantoroRobert KnoxRodrigo Beltran CubilesSaeed AbdaliSai NarayanaSammy MooreSamuele TaruschioSandra SartoriSatish KumarSatish MutyalaSebastian BarkerSerena SoresiSerena ThakerShannon TomlinSheikh AhmedShereef AbdallaSilvia StradaSilvio DistefanoSimone MandicaSlawomir SasSravani LagulaSreenivas BhumireddySreenivas Test SSOSreenivas YSreenivasula ReddySRI Krishna DomaStanislava MarusicStefano PieroniStephen RosserStratos TheodorouSudheer AllaSulwen VaughanSuneel PonugotiSylwester PustelnikTanya CavanaghTeja NarayanaThomas LukinsThomas ShapleyTimothy BellTomas LeakeTony UngerUsman ShaikUttam SahaVaibhav MehtaVaibhav SahuValeria ParrellaVamsi MenduVictor ZanniVictoria MakdesiVijayraghavan VVivek SrivatsanVolkan OzgurWendy YauYurii Lobatiuk                ')]</value>
      <webElementGuid>e4987e10-1cce-45e4-9dae-e33e844858f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
