<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_StartDateAndTime</name>
   <tag></tag>
   <elementGuidId>be65c960-4cfd-45e2-9b6c-9caab196104b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#startdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;dd/mm/yyyy hh:mm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ca5d654-d38c-4d08-bc91-aaecb6039df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>425eb7e7-270c-445d-8fa3-dcd6299650f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startdate</value>
      <webElementGuid>49fda51f-e23e-40bf-80c3-c7057774c6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>startdate</value>
      <webElementGuid>94af55ab-e90e-4bd2-837a-f6a77136f887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datetime-picker</value>
      <webElementGuid>d66227f6-d0b9-420e-8d9a-c945c45c51db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy hh:mm</value>
      <webElementGuid>956f8bad-f96d-4529-b357-4233d43f8977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startdate&quot;)</value>
      <webElementGuid>33501d7d-f4f6-4044-ba3f-fe8164234e1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startdate']</value>
      <webElementGuid>3ea71c2a-cb5a-425d-95de-17ab91e3dfcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[6]/input</value>
      <webElementGuid>6daee4d0-7825-492f-b05b-4e1e362f48eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>acb64401-2591-479c-9174-3975eae666e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'startdate' and @name = 'startdate' and @placeholder = 'dd/mm/yyyy hh:mm']</value>
      <webElementGuid>ed8bc786-9e85-452a-adb3-759998810a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
