<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ProjectedOpExcost</name>
   <tag></tag>
   <elementGuidId>6b7d6bcf-38cd-40fe-a79e-0f06dd5e258e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#projected_opex_cost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='projected_opex_cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#projected_opex_cost</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6f6d5a4-e443-4188-b038-c73a5e74bb35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>07a049bf-2a03-4287-ba6e-13cf3a321f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>projected_opex_cost</value>
      <webElementGuid>ba44a49c-7043-43ec-9324-3fc1f1e563e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>projected_opex_cost</value>
      <webElementGuid>d9d96012-53d2-4d2b-bab9-50be30ba84a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>64962884-5115-4cff-a324-44e0cadcefd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateMaxValue(this)</value>
      <webElementGuid>5ab4dfb0-ee8d-4d08-bfa7-d215c60ab740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999999.99</value>
      <webElementGuid>84cd67c4-4860-40c8-aa03-7281fecf5447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>ee258221-3ec6-4eec-b752-dd9b33615111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projected_opex_cost&quot;)</value>
      <webElementGuid>1fdc54f4-5db6-465b-8fe5-b81c766ff8df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='projected_opex_cost']</value>
      <webElementGuid>488422e4-d033-41b0-aed3-4e6f9d948912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_content']/div/div[2]/div[3]/input</value>
      <webElementGuid>0b0c5000-48ac-44b1-8782-f692ce834feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>15ca6c02-df93-42a5-a215-45d44efcd98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'projected_opex_cost' and @name = 'projected_opex_cost']</value>
      <webElementGuid>9a73bb66-53e7-4151-b47d-0d43eb1f4bc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
