<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ActualCapExcost</name>
   <tag></tag>
   <elementGuidId>17d11317-f8f7-4009-a58c-df9b3e5cf6ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#actual_capex_cost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='actual_capex_cost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#actual_capex_cost</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc046dac-dec3-44fb-bde5-94e797a6904d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7aec1540-c2b3-40e5-ab5f-c234db244eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>actual_capex_cost</value>
      <webElementGuid>7702a49c-db46-494f-b7ff-2cb4879a6493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actual_capex_cost</value>
      <webElementGuid>1ebcb943-17a5-4702-a84d-e17bbe8fd18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>24724ad7-d001-46a8-a0e1-6da5f7c1b1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateMaxValue(this)</value>
      <webElementGuid>ab230c00-46bf-47c6-bf45-139bac3ee1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>999999999.99</value>
      <webElementGuid>fc4b4609-9cb1-41a8-ad26-4ea0a2c3aa65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.01</value>
      <webElementGuid>6e6ff11f-133b-4745-a4c2-daf9d4399f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actual_capex_cost&quot;)</value>
      <webElementGuid>abf8f599-4b5b-480f-a72e-89798fe5ae1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='actual_capex_cost']</value>
      <webElementGuid>d45d0797-da99-4898-882e-7f5d5be716d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='view_content']/div/div[2]/div[2]/input</value>
      <webElementGuid>1bdb0201-ac5b-40cb-84ee-47ef1a692e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>36bbbe6f-b049-4f3e-8d31-87e9602f9de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'actual_capex_cost' and @name = 'actual_capex_cost']</value>
      <webElementGuid>995bd053-b8ae-446c-852c-a2de34d488c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
