<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ResolutionDate</name>
   <tag></tag>
   <elementGuidId>ac3edc70-3b14-4f43-8541-6cf43090c37e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resolutiondate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='resolutiondate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;dd/mm/yyyy&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e26240bb-5d02-49c9-a7d5-75cd379463d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>849c9f06-59e6-4ff3-b687-882b64a681de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resolutiondate</value>
      <webElementGuid>7ba85b70-a2b3-45af-abe8-b5ce44562f6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resolutiondate</value>
      <webElementGuid>04c4cf1d-c054-4fa3-bb2f-083378e4b7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control default-datepicker escalationdate reminderperiod</value>
      <webElementGuid>00ac0e1d-2792-4737-8035-0561915b5127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>dd/mm/yyyy</value>
      <webElementGuid>0079a2b5-56a9-484d-b363-0d667c5deea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resolutiondate&quot;)</value>
      <webElementGuid>b9b07d56-2a36-472b-a338-84ab91a254a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='resolutiondate']</value>
      <webElementGuid>64524ea2-c280-42d5-9be3-70b8670bece1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm_action']/div[2]/div/div[2]/div[7]/input</value>
      <webElementGuid>cbb17907-567e-4434-a0c9-12ec40eb7f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>c09f26e9-61b7-4fe9-b0b9-fa5750ea58e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'resolutiondate' and @name = 'resolutiondate' and @placeholder = 'dd/mm/yyyy']</value>
      <webElementGuid>18d45568-94d1-4451-ac41-fd14467880d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
